### ISSUE TITLE
move setup in yaml

### ISSUE THREAD

**Issue by obar1** [obar1/onepage_job_lister#3]
from 
def get_engines() -> dict:

to  some 
```yaml
justjoin:
  id: justjoin
  template: https://justjoin.it/job-offers/all-locations?keyword=$input_text&from=0

inhire:
  id: inhire *
  template: https://inhire.io/?roles=big_data

solid jobs:
  id: solid jobs
  template: https://solid.jobs/offers/it;searchTerm=$input_text

```
